name: Deploy to Google Cloud

on:
  push:
    branches:
      - main # Se ejecuta cuando hay un push en la rama "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '418.0.0' # Versión del SDK, puedes ajustar según necesidad
          project_id: integral-linker-443601-n2 # ID del proyecto de Google Cloud
          service_account_key: ${{ secrets.GCP_CREDENTIALS }} # Credenciales de la cuenta de servicio

      # 3. Autenticar Docker con Google Container Registry (GCR)
      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker --quiet

      # 4. Construir y subir la imagen del backend
      - name: Build and Push Backend Image
        run: |
          docker build -t gcr.io/integral-linker-443601-n2/backend ./backend
          docker push gcr.io/integral-linker-443601-n2/backend

      # 5. Construir y subir la imagen del frontend
      - name: Build and Push Frontend Image
        run: |
          docker build -t gcr.io/integral-linker-443601-n2/frontend ./frontend
          docker push gcr.io/integral-linker-443601-n2/frontend

      # 6. Desplegar la aplicación en Kubernetes
      - name: Deploy to GKE
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/deployment-backend.yaml
          kubectl apply -f k8s/deployment-frontend.yaml
          kubectl apply -f k8s/service-backend.yaml
          kubectl apply -f k8s/service-frontend.yaml

